---
# tasks file for minirole

- firewalld:
        state: disabled
        permanent: yes
        immediate: yes

- selinux:
        policy: targeted
        state: permissive

- name: "yum repository configuration"
  yum_repository:
        name: "{{ item.na }}"
        description: "repos for minikube"
        baseurl: "{{ item.baseurl }}"
        gpgcheck: no
  
  loop:
  - {   baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/" , na: "docker_insttallation" }
  - {   baseurl: "file:///run/media/root/RHEL-8-0-0-BaseOS-x86_64/AppStream" , na: "for_appstraem" }
  - {   baseurl: "file:///run/media/root/RHEL-8-0-0-BaseOS-x86_64/BaseOS" , na: "for_baseos" }
  
- name: "installing docker and conntrack-tools  ..."
  package:
        name: "{{ item.package_name }}"
        state: present
  
  loop:
  - {   package_name: "docker-ce-18.06.3.ce-3.el7.x86_64"   }
  - {   package_name: "conntrack-tools"   }


- name: "downloading binaries ..."
  get_url:
        url: "{{ item.resource_url }}"
        dest: "/root"

  loop:
  - {   resource_url: "https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64"  }
  - {   resource_url: "https://storage.googleapis.com/kubernetes-release/release/v1.20.0/bin/linux/amd64/kubectl"  }

- name: "installing minikube and configuring ..."
  shell:
        cmd: "{{ item.command }}"

  loop:
  - {   command: "sudo install minikube-linux-amd64 /usr/local/bin/minikube"   }
  - {   command: "minikube config set driver none"   }
  - {   command: "minikube start --driver=none --kubernetes-version=v1.20.0 --memory=1800mb"  }
  - {   command: "chmod +x /root/kubectl"   }
  - {   command: "sudo mv /root/kubectl /usr/local/bin/kubectl"   } 


